[project]
name = "norsdb"
version = "0.1.0"
entry = "norsdb.nors"
type = "lib"

description = "NorsDB-databaseplattform med smoke og selftest"
selftest = "norsdb_selftest.no"

[paths]
source = "."
stdlib = "../std"
build = "../build"
