/* Embedded NCBB bundle generated by the bootstrap toolchain.
 * Linked in when NORCODE_NCBB_EMBED is defined at compile time. */
#ifndef NCBB_EMBEDDED_H
#define NCBB_EMBEDDED_H

#include <stddef.h>
#include <stdint.h>

extern const uint8_t norcode_ncbb_data[];
extern const size_t norcode_ncbb_data_size;

#endif
