#!/usr/bin/env python3
"""Export a binary NCBB bundle as a C array source file."""

from __future__ import annotations

import argparse
from pathlib import Path


def _format_bytes(data: bytes, bytes_per_line: int = 16) -> str:
    lines: list[str] = []
    for index in range(0, len(data), bytes_per_line):
        chunk = data[index : index + bytes_per_line]
        line = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {line}")
    return ",\n".join(lines)


def export_ncbb_as_c(input_path: Path, output_path: Path, symbol_prefix: str) -> None:
    data = input_path.read_bytes()
    array_name = f"{symbol_prefix}_data"
    size_name = f"{symbol_prefix}_data_size"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        (
            "/* Auto-generated by tools/export_ncbb_as_c.py. Do not edit. */\n"
            "#include <stddef.h>\n"
            "#include <stdint.h>\n\n"
            f"const size_t {size_name} = {len(data)};\n"
            f"const uint8_t {array_name}[{len(data)}] = {{\n"
            f"{_format_bytes(data)}\n"
            "};\n"
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Input NCBB binary")
    parser.add_argument("output", type=Path, help="Output .c file")
    parser.add_argument(
        "--symbol-prefix",
        required=True,
        help="C symbol prefix, for example 'norcode_bootstrap_ncbb'",
    )
    args = parser.parse_args()
    export_ncbb_as_c(args.input, args.output, args.symbol_prefix)


if __name__ == "__main__":
    main()
