#!/usr/bin/env bash
# tools/generate_build_embed_c.sh — generer build/*_ncb_data.c frå .ncb (utan Python)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

ncbb_to_c() {
    local input="$1"
    local out="$2"
    local size_name="$3"
    local data_name="$4"
    if [ ! -f "$input" ]; then
        printf 'Feil: manglar %s\n' "$input" >&2
        return 1
    fi
    local size
    size="$(wc -c < "$input" | tr -d ' ')"
    {
        printf '/* Auto-generated by tools/generate_build_embed_c.sh. Do not edit. */\n'
        printf '#include <stddef.h>\n'
        printf '#include <stdint.h>\n\n'
        printf 'const size_t %s = %s;\n' "$size_name" "$size"
        printf 'const uint8_t %s[%s] = {\n' "$data_name" "$size"
        od -An -tx1 -v "$input" | awk '
        {
            for (i = 1; i <= NF; i++) {
                if (count > 0) printf ", "
                if (count % 16 == 0) printf "\n    "
                printf "0x%s", $i
                count++
            }
        }
        END { printf "\n};\n" }
        '
    } > "$out"
}

mkdir -p "$ROOT/build"

ncbb_to_c \
    "$ROOT/build/bootstrap_compiler_bundle.ncb" \
    "$ROOT/build/bootstrap_compiler_bundle_ncb_data.c" \
    norcode_bootstrap_ncbb_data_size \
    norcode_bootstrap_ncbb_data

ncbb_to_c \
    "$ROOT/build/native_elf_compiler_bundle.ncb" \
    "$ROOT/build/native_elf_compiler_bundle_ncb_data.c" \
    norcode_ncbb_data_size \
    norcode_ncbb_data

printf '✓ Genererte build/*_ncb_data.c\n'
